"""Context distillation.

Extremely simple v0 implementation:
- Scans the project tree (respecting simple ignores)
- Builds a small, readable .context.md summary
- Everything stays in plain files

No embeddings, no DBs. Future versions can get smarter while staying sidecar-first.
"""

from pathlib import Path
from typing import List
import os

from .sidecars import (
    read_context, write_context, read_awareness, write_awareness,
    SIDECAR_CONTEXT, SIDECAR_AWARENESS, SIDECAR_MEMORY_DIR, AETHER_DIR
)

IGNORES = {
    ".git", ".aether", "__pycache__", ".mypy_cache", "node_modules",
    ".venv", "venv", ".env", ".DS_Store", ".awareness.json", ".context.md",
    ".memory"
}

def should_ignore(name: str, path: Path) -> bool:
    if name.startswith(".") and name not in {".context.md", ".awareness.json", ".memory"}:
        # still allow our own sidecars but ignore other dot-dirs by default
        if path.is_dir() and name not in {".memory"}:
            return True
    return name in IGNORES or name.endswith(".pyc")

def collect_files(root: Path, max_files: int = 200) -> List[Path]:
    files: List[Path] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if not should_ignore(d, Path(dirpath) / d)]
        for fn in filenames:
            p = Path(dirpath) / fn
            if should_ignore(fn, p):
                continue
            rel = p.relative_to(root)
            if any(part in IGNORES for part in rel.parts):
                continue
            files.append(rel)
            if len(files) >= max_files:
                return files
    return files

def distill(root: Path) -> str:
    """Produce a fresh context summary string."""
    files = collect_files(root)
    awareness = read_awareness(root)

    lines = []
    lines.append(f"# Context — {root.name}")
    lines.append("")
    lines.append("**Generated by aether (v0).** Edit this file freely. It is the source of truth.")
    lines.append("")
    lines.append("## Project Location")
    lines.append(f"- Root: `{root}`")
    lines.append("")
    lines.append(f"## Files (sampled, {len(files)} shown)")
    for f in sorted(files)[:80]:
        lines.append(f"- `{f}`")
    if len(files) > 80:
        lines.append(f"- ... ({len(files) - 80} more)")
    lines.append("")

    # Very naive "understanding" — look for README, package files etc.
    readme = root / "README.md"
    if readme.exists():
        lines.append("## README excerpt")
        content = readme.read_text()[:2000]
        lines.append("```markdown")
        lines.extend(content.splitlines()[:60])
        lines.append("```")
        lines.append("")

    lines.append("## Awareness Stats")
    lines.append(f"- Last awareness update: {awareness.get('last_updated', 'never')}")
    lines.append(f"- Tracked files (approx): {awareness.get('file_count', len(files))}")
    lines.append("")

    lines.append("## Next Steps for Humans / Agents")
    lines.append("- Add high-level goals to this file")
    lines.append("- Create fragments in `.memory/` for important recall")
    lines.append("- Run `aether update` after big changes")
    lines.append("")

    return "\n".join(lines)

def run_distill(root: Path) -> None:
    """Distill and write the sidecar."""
    root = root.resolve()
    files = collect_files(root)

    # Write fresh awareness first so distill() reads up-to-date numbers
    awareness = read_awareness(root)
    awareness["file_count"] = len(files)
    write_awareness(root, awareness)

    summary = distill(root)
    write_context(root, summary)

    print(f"Distilled context for {root}")
    print(f"  → {root / SIDECAR_CONTEXT}")
    print(f"  → {root / SIDECAR_AWARENESS}")
